// Code generated by mockery v2.32.4. DO NOT EDIT.

package future

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// Mock is an autogenerated mock type for the Future type
type Mock struct {
	mock.Mock
}

// Await provides a mock function with given fields: _a0
func (_m *Mock) Await(_a0 context.Context) error {
	ret := _m.Called(_a0)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewMock creates a new instance of Mock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *Mock {
	mock := &Mock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
